---

- name: Create 'ansible' group.
  include: ansible_group.yml
  when: (admin_users is defined) and (admin_users | length > 0)

- name: Create admin users
  include: admin_user.yml
  vars:
    admin_user: "{{ item }}"
  loop: "{{ admin_users }}"
  when: (admin_users is defined) and (admin_users | length > 0)

#  user:
#    name: "{{ admin_user.name }}"
#    comment: "{{ admin_user.comment | default('') }}"
#    groups: "{{ admin_user.groups | default('sudo,adm,ansible') }}"
#    shell: "{{ admin_user.shell | default('/bin/bash') }}"
#    password: "{{ admin_user.password | default('*') }}"
#    state: "{{ admin_user.state | default('present') }}"
#  loop: "{{ admin_users }}"
#  loop_control:
#    label: "{{ admin_user.name }}"
#    loop_var: admin_user
#
#- name: Add authorized_keys
#  become: true
#  authorized_key:
#    user: "{{ item.0.name }}"
#    key: "{{ item.1 }}"
#  with_subelements:
#    - "{{ admin_users }}"
#    - ssh_pub_keys
#  loop_control:
#    label: "{{ item.0.name }}"
#  when: admin_users is defined
