---

- name: Add 'ansible' group
  become: true
  group:
    name: ansible
    state: present

- name: Grant 'ansible' group password-less sudo
  become: true
  template:
    src: files/sudoers.ansible.j2
    dest: /etc/sudoers.d/ansible

